#!/bin/bash

#means symfony_console
sc() {
      docker exec php symfony console "$1"
}

composer() {
      docker exec php composer "$1"
}

unit_tests() {
      docker exec php php bin/phpunit
}

if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi

