#!/bin/bash

#means symfony_console
sc() {
      docker exec php symfony console "$1"
}

watch() {
      docker exec php npm run watch
}

composer() {
      docker exec php composer "$1"
}

analyseCodeAndTests() {
      docker exec php vendor/bin/phpstan analyse  src/  tests/

}

analyseCode() {
      docker exec php vendor/bin/phpstan analyse  src/ --level 9
}

unitTests() {
      docker exec php php bin/phpunit
}

if declare -f "$1" > /dev/null
then
  # call arguments verbatim
  "$@"
else
  # Show a helpful error
  echo "'$1' is not a known function name" >&2
  exit 1
fi

